import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from precomput_analysis_funcs import \
    plot_variance_expl_plot, clustering_after_pca, tsne_after_pca, \
    nmf_then_save, ica_then_save
import argparse
import os
import hyperparam_functions as hpf
import matplotlib.pyplot as plt

pd.options.mode.chained_assignment = None  # default='warn'

def parse_args():
    parser = argparse.ArgumentParser(
        description='args for plotting')
    parser.add_argument(
        '--interpreting_params_name', type=str,
        default='defaults')
    args = parser.parse_args()
    return args


def run():
    args = parse_args()
    hp = hpf.load_interp_configs(args.interpreting_params_name)

    num_episodes = hp.analysis.agent_h.num_episodes  # number of episodes to make plots for
    num_generated_samples = hp.analysis.agent_h.num_generated_samples # number of generated samples to use
    num_epi_paths = hp.analysis.agent_h.num_epi_paths  # Number of episode to plot paths through time for. Arrow plots.
    n_components_pca = hp.analysis.agent_h.n_components_pca
    n_components_tsne = hp.analysis.agent_h.n_components_tsne
    n_components_nmf_or_ica = hp.analysis.agent_h.n_components_nmf_or_ica#32
    n_clusters = hp.analysis.agent_h.n_clusters#40##100
    path_epis = list(range(num_epi_paths))

    # Prepare load and save dirs
    main_data_path = hp.data_dir
    generated_data_path = hp.generated_data_dir + hp.analysis.agent_h.informed_or_random_init
    save_path = 'hx_analysis_precomp/'
    save_path = os.path.join(os.getcwd(), "analysis", save_path)
    plot_save_path = 'hx_plots'
    plot_save_path = os.path.join(os.getcwd(), "analysis", plot_save_path)
    os.makedirs(save_path, exist_ok=True)
    os.makedirs(plot_save_path, exist_ok=True)

    # Get (true) hidden states that were generated by the agent interacting
    # with the real environment
    hx = np.load(os.path.join(main_data_path, 'episode_00000/hx.npy'))
    hx = hx[1:] # Cut 0th timestep
    for ep in range(1, 1000):
        print(ep)
        hx_to_cat = np.load(os.path.join(main_data_path,
                                         f'episode_{ep:05d}/hx.npy'))
        hx_to_cat = hx_to_cat[1:]  # Cut 0th timestep
        hx = np.concatenate((hx, hx_to_cat))

    # Get hidden states the were produced by the generative model
    gen_hx = np.load(os.path.join(generated_data_path, 'sample_00000/agent_hs.npy'))
    for ep in range(1, 3000): #num_generated_samples):
        print(ep)
        gen_hx_to_cat = np.load(os.path.join(generated_data_path,
                                         f'sample_{ep:05d}/agent_hs.npy'))
        gen_hx = np.concatenate((gen_hx, gen_hx_to_cat))

    # PCA
    print('Starting PCA...')
    uncentred_unscaled_hx = hx
    uncentred_unscaled_gen_hx = gen_hx

    mu = np.mean(uncentred_unscaled_hx, axis=0)
    std = np.std(uncentred_unscaled_hx, axis=0)

    centred_scaled_hx = (uncentred_unscaled_hx - mu ) / std
    centred_scaled_gen_hx = (uncentred_unscaled_gen_hx - mu) / std

    pca_obj = PCA(n_components=n_components_pca)
    centred_scaled_hx_pca = pca_obj.fit_transform(centred_scaled_hx)
    centred_scaled_gen_hx_projected = pca_obj.transform(centred_scaled_gen_hx)

    # For future reference the following returns an array of mostly True:
    # np.isclose(pca_obj.transform(centred_scaled_hx),
    #            centred_scaled_hx @ (pca_obj.components_.transpose()),
    #            atol=1e-3)

    print('PCA finished.')
    num_views = 5
    for view in range(num_views):
        # Create grid of plots
        pca_alpha = 0.5
        fig = plt.figure()
        fig.subplots_adjust(hspace=0.8, wspace=0.8)
        fig.set_size_inches(25., 18.)
        ax = fig.add_subplot(1, 1, 1)
        splot = plt.scatter(centred_scaled_hx_pca[:, view],
                            centred_scaled_hx_pca[:, view + 1],
                            s=0.5, alpha=pca_alpha * 0.5)
        splot = plt.scatter(centred_scaled_gen_hx_projected[:, view],
                            centred_scaled_gen_hx_projected[:, view + 1],
                            c='red',
                            s=0.5, alpha=pca_alpha)
        fig.colorbar(splot, fraction=0.023, pad=0.04)
        ax.set_frame_on(False)

        fig.tight_layout()
        fig.savefig(
            f'{os.getcwd()}/analysis/hx_plots/agent_h_overlap_{view}.png')
        plt.close()

if __name__ == "__main__":
    run()
